### ISSUE TITLE
Support indentation of prompts

### ISSUE THREAD

**Issue by jr-cologne** [terkelg/prompts#191] opened 2019-08-18 10:13 UTC
Hi there,

before starting out with my feature request, I just want to let you know what a nice looking and helpful library you have created. Thanks to the well documented functionality in your README, it is really easy to get started with. Overall, it's simply an amazing experience to work with your library. Thank you!

### Is your feature request related to a problem?
Currently, there is no way to indent a single prompt or even better all prompts. All prompts directly start on the left side of the terminal which sometimes doesn't look so well, especially if the terminal window is quite large.

### Describe the solution you'd like
I would really like to see an option to indent prompts by a certain amount of characters/spaces.

### Describe alternatives you've considered
An alternative might be to introduce some kind of global margin which pushes everything away from the edges of the terminal.

### Additional context
I already started looking at your code in order to see if there is an easy way to implement the indentation feature. Unfortunately, I am not very experienced in JS which is why I had some trouble figuring out your code.
Though, I have noticed a few things I just want to point out here:

Most of the prompt elements should be very easy to indent thanks to the `cursor.to(0)` when rendering the prompt (e.g. the text prompt in [line 177](https://github.com/terkelg/prompts/blob/master/lib/elements/text.js#L177)).

Because of this, one could implement an `indentation` property which either uses the default value `0` or a value defined via an `indent` option similar to this line which would probably be placed inside the `elements/prompt.js` file in the constructor:

```js
this.indentation = opts.indent || 0;
```

This could then be used to replace `cursor.to(0)` with `cursor.to(this.indentation)`.

Unfortunately, this simple process of rendering a prompt is not the case in the multiselect prompts, but I feel like it would also be no big deal for you to implement an indentation there.

A downside of the indentation solution is that one would need to specify the wanted indentation over and over again on each prompt.
In case there would be any chance to set a global indentation option which would automatically indent every prompt by the specified amount, this would be totally fine.

The alternative to this would be the margin solution, but regarding this I have no idea whether this is even possible or fairly easy to implement.

In case you would support this small enhancement to your library, I would be happy to implement the indentation feature by myself, but I would probably need some help at some point. If it's easier for you to implement this feature on your own, this is of course absolutely fine as well.

Well, thank you so much for considering my feature request. I hope I have explained everything understandably and I am looking forward to answering any questions you might still have.

Thank you in advance and best regards,
@jr-cologne

**Comment by DrunkenPoney** [comment] 2019-08-20 16:33
I'm pretty sure we can't simply do `cursor.to(this.indentation)`. Doing so would only work for the first line since `cursor.to(0)` resets the cursor to the beginning of the line but it also moves as text is sent to the output.

Though, it is certainly possible to implement such a feature. In fact, it is already partially implemented. See [here](https://github.com/terkelg/prompts/blob/e1f3944345d9d442efc737be0e8d9273885a6867/lib/util/wrap.js#L6)

**Comment by jr-cologne** [comment] 2019-08-20 17:40
Hi @DrunkenPoney,

this looks very interesting. I haven't spotted this.
Thank you for pointing that out.

So, what do you exactly mean by "partially implemented"? What's the current state?
Is there anything I can do to drive things forward?

Have a nice day!
Best regards,
@jr-cologne

**Comment by terkelg** [comment] 2019-08-21 12:37
Thank you @DrunkenPoney. I'm closing this for now

**Comment by jr-cologne** [comment] 2019-08-21 12:57
Hi @terkelg,

may I ask why you are directly closing this issue without reacting to my questions about this enhancement?
For me, this looks like you are not really interested in implementing this feature or you want to implement this somewhere in the future for yourself.
When I am asking whether I can help moving this feature forward, it would be kinda nice to get a response whether contributions are welcome or not.
Just closing this issue is a bit rude, in my opinion.

Best regards,
@jr-cologne

**Comment by terkelg** [comment] 2019-08-21 13:56
Sorry, didn't mean to come off as rude. Your issue was labeled as a potential future enhancement and @DrunkenPoney, which is one of the main contributors had responded to your issue. That being said I was in a hurry and do agree I closed this one too fast – my bad!

Contributions and especially PRs are always welcome. I won't have time to implement this particular feature myself and there are issues and features with bigger priorities at the moment. This is something I could see make it into the next major release where I would love to do a rewrite of Prompts with a propper render engine

**Comment by jr-cologne** [comment] 2019-08-21 14:18
Hi @terkelg,

all right, no problem!
Thank you for reopening this as well as responding to me.

I will definitely take a closer look at this enhancement.
I'm not sure whether my JS skills are enough for this, but I might just go ahead and try to implement this on my fork.
In case I come up with a reasonable solution which could be used until the release of the next major version, I would then reach out to you by submitting a PR.

So, for the sake of keeping this repository clean, feel free to close this issue now. 😄 

Have fun and keep up the good work!

Best regards,
@jr-cologne

**Comment by terkelg** [comment] 2019-08-22 14:27
Thank you @jr-cologne – you can always reach out to me if you have questions. My DM is open on twitter

**Closed by terkelg** 2019-08-22 14:27 UTC
Labels: enhancement

**Comment by jr-cologne** [comment] 2019-10-25 20:36
Hi there!

I just tried to implement a margin / an indentation feature for single prompts using the `wrap` functionality you mentioned.
Unfortunately, I have come across some weird issues I couldn't really figure out.
I kinda got the feature to work, but it's more like a workaround since I encountered some issues when it comes to always getting the right amount of spaces you've specified.
I would be really happy if someone would have the time to take a look at this.

This is the Draft PR on my fork: https://github.com/jr-cologne/prompts/pull/1

Thank you very much in advance!

Best regards,
@jr-cologne

**Comment by jr-cologne** [comment] 2019-11-08 21:44
Hi @terkelg and @DrunkenPoney,

I'm sorry for directly mentioning you.
I just want to make sure you are aware of my last comment since I'm not sure whether a comment in a closed issue even triggers a notification on GitHub.
So, please don't understand this as a call to tackle this issue.
There are off course way more important issues.

Again, apologies for interrupting. Have a nice weekend!

Best regards,
@jr-cologne

**Comment by terkelg** [comment] 2019-11-09 02:28
Thanks for the mention. I didn't receive any notifications on this and totally wasn't aware of your last comments. I personally feel this is a bit of a niche feature and not something we should implement at the moment.  The problem is that over time more and more features sneak into the codebase and they all add up. Complexity grows and makes it harder to maintain. I will however take this into consideration for the rewrite. Future versions of prompts might provide a better way to render prompts with more options for customization – like indentation

**Comment by jr-cologne** [comment] 2019-11-09 07:30
All right, totally understand that.
Thank you for the reply!
