### ISSUE TITLE
Selection skips elements, selection not possible

### ISSUE THREAD

**Issue by FloMaetschke** [terkelg/prompts#148] opened 2019-03-08 02:06 UTC
### Describe the bug

When i press the down arrow, it directly jumps to the third entry (skips 1 element).
To get the correct selection its like playing roulette, holding down the button for a few seconds and releasing it randomly until hopefully it selects the correct entry.
This is a really annoying usability issue.

### To Reproduce

1. Using 'ng new project' or 'strapi new project' or any other tool using prompts
2. Try to select the second element

### Expected behavior

When i press the down-arrow button ony my keyboard, the element below the current element should be selected (or if it is the last one, the first one).

### System

- OS: Windows 10 
- Terminal: cmd.exe, git-bash, powershell
- Node version: 11.9

### Additional context

Do you have any idea why this happens? Other editors and tools work fine. There is no double key event.
For example, when i navigate in githubs text-editor up and down it works fine and absolute exactly.

I am using a Corsair K68 keyboard.

**Comment by lumio** [comment] 2019-03-11 20:53
Just tested this on a Mac OS with the latest @angular/cli
It looks like a Windows only problem? Will try to reproduce this on a Windows VM.

If anyone else has an idea, feel free to comment :)

**Comment by lumio** [comment] 2019-03-11 21:23
So far I cannot directly reproduce it.

Tested `ng new project` with

- `PowerShell`
- `cmd`
- `cmder`

However, `git-bash` has some issues as it wouldn't even show the prompts and go straight to creating a new project. Which is weird as I created the following and working test script:

```js
const prompts = require( 'prompts' );

( async () => {
  const result = await prompts( {
    type: 'select',
    name: 'selected',
    message: 'Test',
    choices: [
      { title: 'Test1', value: 1 },
      { title: 'Test2', value: 2 },
      { title: 'Test3', value: 3 },
    ],
  } );
  console.log( result );
} )();
```

@FloMaetschke can you try and run the script above and test if it works on your end?

**Comment by terkelg** [comment] 2019-03-16 16:10
Thank you @lumio. Closing this one

**Closed by terkelg** 2019-03-16 16:10 UTC
