### ISSUE TITLE
Arrow keys not working for the "select" prompt type

### ISSUE THREAD

**Issue by DrunkenPoney** [terkelg/prompts#75] opened 2018-07-24 20:05 UTC
Pressing the arrow keys to change the selected value in a prompt of type _select_ does not work visually. The initial value remains the one selected / colored. Though, when I press enter/return it does not necessarily return the initial value. In other words, pressing the arrow keys changes the selected value but does not change the highlighted line in console / terminal.

<hr>

 **Edit:**
Arrow keys work in a DOS terminal but not in bash

**Comment by terkelg** [comment] 2018-07-27 07:59
Thanks for reporting the issue. weird, I can't reproduce this in bash

**Comment by DrunkenPoney** [comment] 2018-08-01 03:49
I think it's cause I was using a **mintty** bash terminal. 😊

**Comment by DrunkenPoney** [comment] 2018-08-01 03:49
I think it's cause I was using a **mintty** bash terminal. 😊

**Comment by terkelg** [comment] 2018-08-01 10:24
No biggie. I'll close the issue for now

**Closed by terkelg** 2018-08-01 10:24 UTC
Labels: bug
